#!/usr/bin/env bash
# prints 1 to 20 with some other stuff
index=1
while ((index < 21))
do
  echo $index
  case $index in
    4)
      echo "bad luck from China"
      ;;
    9)
      echo "bad luck from Japan"
      ;;
    17)
      echo "bad luck from Italy"
      ;;
  esac
  index=$((index+1))
done
