#!/usr/bin/env bash
# prints up to 12:59
hour=0
minute=1
while ((hour < 13))
do
  if ((minute == 1))
  then
    echo "Hour: $hour"
  fi
  echo $minute
  minute=$((minute+1))
  if ((minute == 60))
  then
    minute=1
    hour=$((hour+1))
  fi
done
