#!/usr/bin/env bash
# Gives information on holbertonschool file
check="holbertonschool"
if [ -e $check ]
then
  echo "holbertonschool file exists"
  if [ -s $check ]
  then
    echo "holbertonschool file is not empty"
  else
    echo "holbertonschool file is empty"
  fi
  if [ -f $check ]
  then
    echo "holbertonschool is a regular file"
  fi
else
  echo "holbertonschool file does not exist"
fi
