#!/usr/bin/env bash
# file transfer to server
nums=("$#")
args=("$@")
if ((nums < 3))
then
  Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
  exit
fi
if [ -z "${args[3]}" ]
then
    scp -o StrictHostKeyChecking=no "${args[0]}" "${args[2]}@${args[1]}":~/
else
    scp -o StrictHostKeyChecking=no -i "${args[3]}" "${args[0]}" "${args[2]}@${args[1]}":~/
fi
