#!/usr/bin/env bash
# Configures new ubuntu machine with nginx
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo "hello Holberton School hello Holberton School hello Holberton School" | sudo tee /usr/share/nginx/html/index.html
wget https://raw.githubusercontent.com/c-eng/holberton-system_engineering-devops/master/0x0B-web_server/default-1
mv default-1 default
mv default /etc/nginx/sites-available
sudo service nginx restart
