#!/usr/bin/env bash
# Configure nginx to run as nginx user
pkill apache2
chown nginx /etc/nginx/nginx.conf
chgrp nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i 's/80 default/8080 default/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
